version: "2"
services:
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
  odoo:
    image: odoo
    ports:
      - 8069:8069
    depends_on:
      - db
    links:
      - db:db
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./web_data:/var/lib/odoo
  pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      - db
    links:
      - db:db
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=andrei.costea47@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=odoo
